<h1>About LCWO - Learn CW Online</h1>
<? if ($_SESSION['lang'] != 'en') {
?>
<p>(only in English for now)</p>
<?
}
?>
<p>This site, <em>Learn CW Online</em> (LCWO), was established in May 2008 by 
<a href="http://fkurz.net/">Fabian Kurz, DJ1YFK</a> 
(<a href="/impressum">Impressum</a>, 
<a href="http://lcwo.net/profile/dj1yfk">profile</a>),
hoping to make learning and practicing CW (Morse code)
as easy and effortless as possible.</p>

<p>LCWO is under constant development; all comments and
suggestions are welcome. To get in touch with the author, use the <a
href="/impressum#form">contact form</a> or send an email to <a
href="mailto:help&#64;lcwo.net">help&#64;lcwo.net</a>. For
general questions and discussion, feel free to use the <a
href="/forum">forum</a>.  Thanks to all
the users who contributed to the project so far. Without all the
feedback the site wouldn't be what it is today!</p>

<p><strong>Using LCWO is and will always remain free of
cost.</strong> We are not interested in monetary donations.
</p>

<h2>Translators</h2>
<p><em>Many thanks</em> to following persons for translating the user interface
to new languages:</p>

<? include("inc/about-translators.php"); ?>


<p>If you like to help to translate LCWO to another language,
please <a href="mailto:help&#64;lcwo.net">get in touch with Fabian, DJ1YFK via
email</a>. Thanks!</p>
<h2>Spread the word!</h2>
<p>If you like to link to LCWO from your website or blog, you may
want to use one of the following banners or buttons. Also high
resolution logos (b/w) are available for QSL cards.</p>
<div>
Banner, 468x60px: <br><img src="/pics/lcwo-banner.png" alt="[LCWO Banner]"><br><br>
Buttons, 80x15px: <br>
<img src="/pics/lcwo-button1.png" alt="[LCWO Button 1]">&nbsp; <img
src="/pics/lcwo-button2.png" alt="[LCWO Button 2]"><br><br>
Logos for QSL cards (ZIP file with several formats, PDF, EPS,
PNG):<br>
<a href="/pics/qsl-logos.zip"><img
src="/pics/qsl-logo-small.png" alt="[LCWO print logo]"></a><br><br>
</div>

<h2 id="rate">Reviews / Ratings</h2>

<table width="80%">
<tr>
<td valign="top" width="45%">
<a href="http://www.eham.net"><img style="border:none;" src="/pics/ehamlogo.gif" alt="[eham.net logo]"></a><br>
<p>This site has been reviewed (<?=$eham1?> from <?=$eham2?> reviews) on eHam.net. <br><a
href="http://www.eham.net/reviews/detail/8401">Thanks, and please
add your own review if you like!</a></p>
<p>You may also want to rate LCWO on eHam's <a
href="http://www.eham.net/links/rating/10889">links section</a>.</p>
</td>
<td width="10%">
&nbsp;
</td>
<td width="45%">
<? include("dxzone.html"); ?>
</td>
</tr>
</table>

<h2>Press release</h2>
<p>Feel free to use the following announcement of LCWO for your club
newsletter, website, blog, etc.</p>

<pre style="border:1px solid #aaaaaa; margin:3px">
<? include("lcwo.txt"); ?>
</pre>


<h2>Browser compatibility, technical stuff</h2>

<p>LCWO supports all modern browsers (Firefox, Chrome, Safari) and it known to work with Edge and Opera.</p>

<p>Development of LCWO takes place under <a
href="http://www.debian.org/">Debian GNU/Linux</a> and <a
href="http://www.ubuntu.com">Ubuntu</a>, using the fantastic <a
href="http://www.vim.org/">vim</a> editor. The site runs on an <a
href="http://www.apache.org/">Apache</a> Webserver, is mostly programmed in <a
href="http://www.php.net/">PHP</a> (without any frameworks, all homebrew) and
uses a <a href="http://www.mysql.com/">MySQL</a> database. The Morse code is
generated by <a href="https://fkurz.net/ham/jscwlib.html">jscwlib</a>, the
downloadable Morse MP3 and OGG files are generated by customized versions of <a
href="http://fkurz.net/ham/ebook2cw.html">ebook2cw</a> which run as compiled
CGIs, written in C.</p>

<p>LCWO is Open Source and you can find the source code at <a href="https://git.fkurz.net/dj1yfk/lcwo">https://git.fkurz.net/dj1yfk/lcwo</a>.</p>
